.TH NAV 1
.SH NAME
nav \- a highly configurable, performant, async system tool
.SH SYNOPSIS
.IX Header "SYNOPSIS"
\&\fBnav\fR [\fB\-\-version\fR] [\fB\-\-help\fR] [\fB\-\-debug\fR]
.TP
\&\fBnav\fR [\fB\-\-config\fR=\fIpath\fR] [\fB\-\-log-file\fR=\fIpath\fR] [\fB\-\-verbose\fR=\fIgroup\fR]
.SH DESCRIPTION
nav is a hackable ncurses file manager, inspired by vim, ranger, and dvtm.

nav searches for a config file in the following order:
  \fB~/.navrc\fP
  \fB~/.nav/.navrc\fP
  \fB/etc/navrc\fP

.SH OPTIONS
.IP "\fB\-c\fR \fIpath\fR, \fB\-\-config\fR=\fIpath\fR" 14
.IX Item "--config=path"
Specify an alternative config file.
.IP "\fB\-l\fR \fIpath\fR, \fB\-\-log-file\fR=\fIpath\fR" 14
.IX Item "-l, --log-file"
Specify an alternative log file
(Sets \fB--debug\fP).
.IP "\fB\-V\fR \fIgroup\fR, \fB\-\-verbose\fR=\fIgroup\fR" 14
Verbose mode for a specific log group
(Sets \fB--debug\fP).
.IX Item "-V, --verbose"
.IP "\fB\-d\fR, \fB\-\-debug\fR" 14
.IX Item "--debug"
Debug mode.
.IP "\fB\-v\fR, \fB\-\-version\fR" 14
.IX Item "--version"
Print version information and exit.
.IP "\fB\-h\fR, \fB\-\-help\fR" 14
.IX Item "-h, --help"
Print this help message and exit.

.SH DEFAULT KEYS
.SS "\s-1Buffer\s0"
.IP "\fBh\fR"
go left
.IP "\fBj\fR"
go down
.IP "\fBk\fR"
go up
.IP "\fBl\fR"
go right
.IP "\fBC-j\fR"
jump page down
.IP "\fBC-k\fR"
jump page up
.IP "\fBn\fR"
next search result
.IP "\fBN\fR"
previous search result
.IP "\fBC-o\fR"
jumplist cycle backward
.IP "\fBC-i\fR"
jumplist cycle forward
.IP "\fBg\fR"
g operator
.IP "\fBG\fR"
goto bottom
.IP "\fBV\fR"
toggle visual select
.IP "\fBy\fR"
yank operator
.IP "\fBd\fR"
cut operator
.IP "\fBm\fR"
mark operator
.IP "\fB’\fR"
jump operator
.IP "\fBp\fR"
paste
.IP "\fBX\fR"
remove

.RE
.SS "\s-1Window\s0"
.IP "\fBH\fR"
move window focus left
.IP "\fBJ\fR"
move window focus down
.IP "\fBK\fR"
move window focus up
.IP "\fBL\fR"
move window focus down
.IP "\fB:\fR"
start command-line mode
.IP "\fB/\fR"
forward search
.IP "\fB?\fR"
backward search

.RE
.SS "\s-1Term\s0"
.IP "\fBMeta-[\fR"
escape terminal focus
.IP "\fBMeta-k\fR"
scroll buffer up
.IP "\fBMeta-j\fR"
scroll buffer down

.RE
.SS "\s-1Command-line\s0"
.IP "\fBESC\fR"
cancel/close ex_mode
.IP "\fBTAB\fR"
compl cycle forward
.IP "\fBS-TAB\fR"
compl cycle backward
.IP "\fBCAR\fR"
run cmd
.IP "\fBBS\fR"
(internal)
.IP "\fBSpc\fR"
(internal)
.IP "\fBC-p\fR"
history cycle backward
.IP "\fBC-n\fR"
history cycle forward
.IP "\fBC-w\fR"
delete word
.IP "\fBC-u\fR"
delete line
.IP "\fBC-l\fR"
add invert symbol to cmd
.IP "\fBC-g\fR"
hint mode
.IP "\fBC-j\fR"
go down in menu
.IP "\fBC-k\fR"
go up in menu

.RE
.SS "\s-1Operator\s0"
.IP "\fBm\fR {\fIa-zA-Z0-9\fR}"
set mark {\fIa-zA-Z0-9\fR} for path.
.IP "\fB’\fR {\fIa-zA-Z0-9\fR}"
jump to the mark {\fIa-zA-Z0-9\fR}
.IP "\fBC-w\fR {\fBHJKL\fR}"
swap buffer in direction
.IP "\fByy\fR
yank visible field
.IP "\fByf\fR
yank fullpath
.IP "\fByn\fR
yank name
.IP "\fByN\fR
yank name (no extension)
.IP "\fBye\fR"
yank extension
.IP "\fByd\fR"
yank directory
.IP "\fByt\fR"
yank type (opgroup)
.IP "\fByk\fR"
yank kind (file type)
.IP "\fBdd\fR"
yank to delete register

.RE
.SS "\s-1Symbol Expansion\s0"
.IP "\fB%b\fR"
buffer number
.IP "\fB%B\fR"
buffer name
.IP "\fB%f\fR"
fullpath
.IP "\fB%n\fR"
name
.IP "\fB%N\fR"
name (no extension)
.IP "\fB%e\fR"
extension
.IP "\fB%d\fR"
directory
.IP "\fB%t\fR"
type (opgroup)
.IP "\fB%k\fR"
kind (file type)
.IP "\fB%o:<var>\fR"
opgroup variable

.SH FILES
User-local info file: \fI~/.navinfo\fR.
.TP
Global configuration file: \fI/etc/navrc\fR.
.SH BUGS
If you find a bug, please report it at
.br
<\fBhttp://github.com/jollywho/nav\fP>.
.SH AUTHORS
Kevin Vollmer <kvollmer@metaphorize.net>
